### PR TITLE
CODE REVIEW REQUEST FOR APPLE CLONE PROJECT

### PR DESCRIPTION
**Pull request by vanheaven-ui**
Kindly review code for apple clone built using HTML and CSS.  Background images were used for all the images on the page while linear-gradient backgrounds were used for the hover effect and background of the navigation bar.
My email is vanheaven6@gmail.com. I will it to add it to the contact details in the README.

### CODE REVIEW

**Review by men32z — CHANGES_REQUESTED** [review]
Hey @vanheaven-ui !
## Good job on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍
- [ ] [REQUIRED] bottom article images should be aligned with main image in wide screens. 
Screenshot_2020-04-08 Apple page

- [ ] [OPTIONAL] fix this input problem when is focused. 
Screenshot_2020-04-08 Apple page(1)


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@men32z)
I would be happy to help! 👩‍💻

Happy coding 🤓

--Luis Preza

**Comment by vanheaven-ui** [comment]
I have made the changes as stated in the review above. Kindly review the changes.

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 🎈 

Hi @vanheaven-ui, you have done a great job fixing the changes recommended by the previous TSE. On this note, I hereby approve of your project 😄 Congratulations 🎆

[OPTIONAL]
Going forward, let us improve our commit messages by using ```add``` instead of ```added``` or ```fix``` instead of ```fixed```
 
Go ahead and merge to master and submit the project completion form 👌 
Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Comment by vanheaven-ui** [comment]
> ## Commit Messages Tense
> Hi Daniel, 
Thanks a lot for the feedback. However, I am not clear on commit messages, If I modify style rule, shouldn't the commit message explain what I DID(past). Thus appropriate to say "Modified style rule". I will appreciate it if you explain more about this. Cheers

**Pull request merged**
